# Generated by Django 3.1.5 on 2021-05-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPMN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_entitas', models.CharField(max_length=100)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdg.database')),
            ],
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Relasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_relasi', models.CharField(max_length=20)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdg.entitas')),
            ],
        ),
        migrations.CreateModel(
            name='Proses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proses', models.CharField(max_length=50)),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdg.proyek')),
            ],
        ),
        migrations.CreateModel(
            name='Generate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_generate', models.DateTimeField(auto_now=True)),
                ('url_jpg', models.CharField(max_length=100)),
                ('url_png', models.CharField(max_length=100)),
                ('url_svg', models.CharField(max_length=100)),
                ('proyek', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cdg.proyek')),
            ],
        ),
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_data_objek', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('proses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdg.proses')),
            ],
        ),
        migrations.CreateModel(
            name='Atribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_atribut', models.CharField(max_length=100)),
                ('tipe_data', models.CharField(max_length=50)),
                ('entitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdg.entitas')),
            ],
        ),
    ]
