# Generated by Django 3.1.5 on 2021-05-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataobject',
            name='proses',
        ),
        migrations.AddField(
            model_name='bpmn',
            name='nama_bpmn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
