# Generated by Django 3.1.5 on 2021-05-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdg', '0002_auto_20210522_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmn',
            name='proses_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdg.proses'),
        ),
        migrations.AddField(
            model_name='database',
            name='proyek_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdg.proyek'),
        ),
        migrations.AddField(
            model_name='dataobject',
            name='bpmn_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdg.bpmn'),
        ),
    ]
