# Generated by Django 3.1.5 on 2021-05-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdg', '0003_auto_20210522_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bpmn',
            old_name='proses_id',
            new_name='proses',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='proyek_id',
            new_name='proyek',
        ),
        migrations.RenameField(
            model_name='dataobject',
            old_name='bpmn_id',
            new_name='bpmn',
        ),
    ]
