# Generated by Django 3.1.5 on 2021-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdg', '0005_proses_bpmn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='nama_database',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proyek',
            name='database_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='relasi',
            name='berelasi_dengan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
